backendTask/backendTask/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('users.urls')),
    path('swipepic/',include('swipepic.urls')),
]

backendTask/swipepic/urls.py
from django.urls import path
from . import views

app_name = 'swipepic'

urlpatterns = [
    
    path('dashboard/', views.dashboard, name='dashboard'),
    path('history/',views.history,name='history'),
    
    ]

backendTask/users/urls.py
from django.urls import path
from . import views


app_name = 'users'

urlpatterns = [
    
    path('', views.login_view, name='login'),
    path('register/',views.register_view,name='register'),
    path('otp/',views.otp_view,name='otp'),
    # path('dashboard/',views.dashboard_view,name='dashboard')
    ]

backendTask/swipepic/models.py
from django.db import models
from django.contrib.auth.models import User

class ImageHistory(models.Model):
    image_path = models.URLField()
    action = models.CharField(max_length=10, choices=[('accept', 'Accept'), ('reject', 'Reject')])
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.action} - {self.image_path} ({self.user.first_name})"

backendTask/users/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import User
import uuid
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User ,on_delete=models.CASCADE)
    phone_no=models.CharField(max_length=13)
    otp=models.CharField(max_length=6)
    uid=models.UUIDField(default=uuid.uuid4)

backendTask/swipepic/views.py
from django.shortcuts import render, redirect
from .models import ImageHistory
from django.utils import timezone
from django.contrib.auth.decorators import login_required
# Create your views here.
# Image paths and names
image_paths = [
    {'path': '/static/1.png', 'name': 'One'},
    {'path': '/static/2.png', 'name': 'Two'},
    {'path': '/static/3.png', 'name': 'Three'},
    {'path': '/static/4.png', 'name': 'Four'},
    {'path': '/static/5.png', 'name': 'Five'},
]



@login_required(login_url='users:login')

def dashboard(request):
    image_index = request.session.get('image_index', 0)
    last_interaction = request.session.get('last_interaction', str(timezone.now()))

    # Handle button clicks
    if request.method == 'POST':
        # image_index = request.session.get('image_index', 0)
        # last_interaction = request.session.get('last_interaction', str(timezone.now()))
        action = request.POST.get('action')
        current_image = image_paths[image_index]

        if action == 'left':
            # Reject the image
            ImageHistory.objects.create(image_path=current_image['path'], action='reject', user=request.user)
            request.session['last_interaction'] = str(timezone.now())
            message = f"{request.user.first_name}, you have rejected image {current_image['name']}"
            return render(request, 'dashboard.html', {'message': message})
        elif action == 'right':
            # Accept the image
            ImageHistory.objects.create(image_path=current_image['path'], action='accept', user=request.user)
            request.session['last_interaction'] = str(timezone.now())
            message = f"{request.user.first_name}, you have selected image {current_image['name']}"
            return render(request, 'dashboard.html', {'message': message})

    # Check if 5 seconds have elapsed since the last interaction
    time_elapsed = timezone.now() - timezone.datetime.fromisoformat(last_interaction)
    if time_elapsed.total_seconds() >= 5:
        image_index = (image_index + 1) % len(image_paths)
        request.session['image_index'] = image_index
        request.session['last_interaction'] = str(timezone.now())

    # Get the current image path and name
    current_image = image_paths[image_index]

    if image_index == 0 and len(image_paths) == len(ImageHistory.objects.filter(user=request.user).all()):
        message = f"{request.user.first_name}, you have rated all the images. Thank you!"
        return render(request, 'dashboard.html', {'message': message})
   
    context = {
        'image_path': current_image['path'],
        'image_name': current_image['name'],
        'image_index': image_index,
        'total_images': len(image_paths),
        'welcome_message':f'Welcome {request.user.first_name}'
    }
    return render(request, 'dashboard.html', context)

def history(request):
    history = ImageHistory.objects.filter(user=request.user).order_by('-timestamp')
    context = {'history': history}
    return render(request, 'history.html', context)

backendTask/users/views.py
from django.shortcuts import render,redirect
from .models import *
from .sendotp import messagehandler
from django.contrib.auth import login
import random 
# Create your views here.
def register_view(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        name = request.POST.get('name')
        phone_no = request.POST.get('mobile')
        
        check_user = User.objects.filter(email = email).first()
        check_profile = Profile.objects.filter(phone_no = phone_no).first()
        
        if check_user or check_profile:
            context = {'message' : 'User already exists' , 'class' : 'danger' }
            return render(request,'register.html' , context)
            
        user = User(email = email , first_name = name)
        user.save()
        otp = str(random.randint(1000 , 9999))
        profile = Profile(user = user , phone_no=phone_no , otp = otp) 
        profile.save()
        message_handler =messagehandler(phone_no,profile.otp).send_otp_on_phone()
        request.session['phone_no'] = phone_no
        return redirect('/otp')
    return render(request,'register.html')

def login_view(request):
    if request.method == 'POST':
        phone_no = request.POST.get('mobile')
        
        user = Profile.objects.filter(phone_no = phone_no).first()
        
        if user is None:
            context = {'message' : 'User not found' , 'class' : 'danger' }
            return render(request,'login.html' , context)
        
        otp = str(random.randint(1000 , 9999))
        user.otp = otp
        user.save()
        message_handler =messagehandler(phone_no,user.otp).send_otp_on_phone()
        request.session['phone_no'] = phone_no
        return redirect('/otp')        
    return render(request,'login.html')    


def otp_view(request):
    phone_no = request.session['phone_no']
    context = {'mobile':phone_no}
    if request.method == 'POST':
        otp = request.POST.get('otp')
        profile = Profile.objects.filter(phone_no=phone_no).first()
        
        if otp == profile.otp:
            login(request,profile.user)
            return redirect('/swipepic/dashboard/',context)
        else:
            print('Wrong')
            
            context = {'message' : 'Wrong OTP' , 'class' : 'danger','mobile':phone_no }
            return render(request,'otp.html' , context)
            
        
    return render(request,'otp.html' , context)

# for testing
# def dashboard_view(request):
#     return render(request,'dashboard.html')

backendTask/templates/base.html
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <title>{% block title %} Django App {% endblock %}</title>
  </head>
  <body>
    <nav>
      <a href="{% url 'users:login' %}">
        <span role="img" aria-label="login" title="login">🏠Login</span>
      </a>
      |

      <a href="{% url 'users:register' %}">
        <span role="img" aria-label="register" title="register">🚀Register</span>
      </a>
      |
      <a href="{% url 'swipepic:history' %}">
        <span role="img" aria-label="history" title="history">📰History</span> </a
      >|
      <a href="{% url 'swipepic:dashboard' %}">
        <span role="img" aria-label="dashboard" title="dashboard"
          >📩Dashboard
        </span>
      </a>
      |
    </nav>
    <main>{% block content %} {% endblock %}</main>
  </body>
</html>

backendTask/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
Welcome
{{user.first_name}} 
you are loged in 
<img src="{% static '1.png' %}" /> 




{% block content %}
<div class="alert alert-{{class}}">
  <strong>{{welcome_message}}</strong>
 </div>
  <h1>View Images</h1>
  <p>Image {{ image_index|add:1 }} of {{ total_images }}</p>

  <img src="{{image_path }}" alt="{{ image_name }}">

  <form method="post" id="action-form">
    {% csrf_token %}
    <input type="hidden" name="action" id="action-input">
    <button type="submit" name="action" value="left">Reject</button>
    <button type="submit" name="action" value="right">Accept</button>
  </form>
  {% if message %}
        <div class="alert alert-{{class}}">
         <strong>{{message}}</strong>
        </div>
        <p>select/reject more <a href="{% url 'swipepic:dashboard' %}">
          <span role="img" aria-label="dashboard" title="dashboard">dashboard </span>
      </a> </p>
        {% endif %}

        
{% endblock %}

backendTask/templates/history.html
{% extends 'base.html' %}
{% block title %}
History
{% endblock %}
{% block content %}
<h1>Image History</h1>
  <table>
    <thead>
      <tr>
        <th>Action</th>
        <th>Image</th>
        <th>Timestamp</th>
      </tr>
    </thead>
    <tbody>
      {% for entry in history %}
        <tr>
          <td>{{ entry.action }}</td>
          <td><img src={{ entry.image_path }} alt='img' /></td>
          <td>{{ entry.timestamp }}</td>
          <td>{{ user.username}}</td>

        </tr>
      {% endfor %}
    </tbody>
  </table>

{% endblock %}

backendTask/templates/login.html
{% extends "base.html" %} {% block content %}

<div class="container mt-5 pt-4">
  <div class="col-6 mx-auto">
    <h3 class="text-center">Login</h3>
    <form method="post">
      {% csrf_token %}
       {% if message %}
      <div class="alert alert-{{class}}">{{message}}</div>
      {% endif %}
      <div class="row">
        <div class="form-group col-12">
          <input
            type="text"
            placeholder="Mobile"
            class="form-control"
            name="mobile"
            id=""
          />
        </div>
      </div>

      <p>
        Don't have account <a href="{% url 'users:register' %}">Register</a>
      </p>
      <button class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>

{% endblock %}

backendTask/templates/otp.html
{% extends "base.html" %}
{% block content %}



<div class="container mt-5 pt-4">
    
    <div class="col-6 mx-auto">
        <h3 class="text-center">Enter OTP sent to your number </h3>
        {% if message %}
        <div class="alert alert-{{class}}">
            {{message}}
        </div>
        {% endif %}

        <form class="mt-2" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="form-group col-12 mt-3">
                    <input type="text" placeholder="Enter otp" class="form-control" name="otp" id="">
                </div>
            </div>

            <p>Don't have account <a href="{% url 'users:register' %}">Register</a></p>
            <button class="btn btn-primary">Submit</button>
        </form>
    </div>

</div>


{% endblock %}

backendTask/templates/register.html
{% extends "base.html" %} {% block content %}

<div class="container mt-5 pt-4">
  <div class="col-6 mx-auto">
    <h3 class="text-center">Register</h3>
    <form method="post">
      {% csrf_token %} {% if message %}
      <div class="alert alert-{{class}}">{{message}}</div>
      {% endif %}

      <div class="row">
        <div class="form-group col-12">
          <input
            type="text"
            placeholder="Email"
            class="form-control"
            name="email"
            id=""
          />
        </div>
      </div>
      <div class="row">
        <div class="form-group col-12">
          <input
            type="text"
            placeholder="Name"
            class="form-control"
            name="name"
            id=""
          />
        </div>
      </div>
      <div class="row">
        <div class="form-group col-12">
          <input
            type="text"
            placeholder="Mobile"
            class="form-control"
            name="mobile"
            id=""
          />
        </div>
      </div>

      <p>Already have account <a href="{% url 'users:login' %}">Login</a></p>
      <button class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>

{% endblock %}